CREATE DATABASE mobiletea WITH ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
CREATE USER mobiletea WITH ENCRYPTED PASSWORD 'mobiletea2025';
ALTER DATABASE mobiletea OWNER TO mobiletea;
GRANT ALL PRIVILEGES ON DATABASE mobiletea TO mobiletea;
GRANT USAGE,CREATE ON SCHEMA public to mobiletea;
ALTER USER mobiletea CREATEDB CREATEROLE LOGIN;
